version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: apps/api
      dockerfile: apps/money_tracker/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: money_tracker
      NODE_ENV: development
      ENV: prod
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app # Sync source code for live updates
      - /usr/src/app/node_modules

    command: npm run start:dev

