name: Deploy to Dev

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{github.actor}}

jobs:
  version:
    name: Set version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.NODE_AUTH_TOKEN}}
      - name: Build image
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        run: |
          docker build \
            --build-arg NODE_AUTH_TOKEN=$NODE_AUTH_TOKEN \
            --tag ghcr.io/${{ github.actor }}/store:latest \
            .
          docker push ghcr.io/${{ github.actor }}/store:latest

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{secrets.EC2_SSH}}
        run:  |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
      - name: SSH and deploy
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{secrets.EC2_HOST}} << 'EOF'
            echo "${{secrets.NODE_AUTH_TOKEN}}" | sudo docker login ghcr.io --username ${{github.actor}} --password-stdin
            sudo docker pull ghcr.io/${{github.actor}}/store:latest
            sudo docker stop store || true
            sudo docker rm store || true
            sudo docker run -d --name store -p 80:3002 ghcr.io/${{github.actor}}/store:latest
          EOF